apiVersion: 1

datasources:
  - name: DS_PROMETHEUS
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    editable: true
    jsonData:
      timeInterval: "30s"

## EJEMPLO BASE DE DATOS INFLUXDB
  # - name: NombreBaseDeDatosInfluxDB
  #   type: influxdb
  #   access: proxy
  #   url: http://influxdb:8086
  #   database: NombreBaseDeDatos
  #   editable: true
  #   jsonData:
  #     timeInterval: "30s"
